ProjetoM17E/Controllers/ConsultasController.cs
using ProjetoM17E.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjetoM17E.Controllers
{

    public class ConsultasController : Controller
    {
        private ProjetoM17EContext db = new ProjetoM17EContext();
        // GET: Consultas
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PesquisaDinamica()
        {
            return View();
        }
        public JsonResult PesquisaNome(string nome)
        {
            var utilizadors = db.Utilizadors.Where(c => c.Nome.Contains(nome)).ToList();
            return Json(utilizadors, JsonRequestBehavior.AllowGet);
        }

        public ActionResult MelhorCliente()
        {
            string sql = @"SELECT Utilizadors.Nome, count(*) as [Nº Entregas]
                            FROM Entregas INNER JOIN Utilizadors
                            ON entregas.utilizadorid = Utilizadors.UtilizadorId
                            GROUP BY entregas.utilizadorid, utilizadors.Nome
                            ORDER BY count(*) DESC ";

            var melhor = db.Database.SqlQuery<Campos>(sql);
            if (melhor != null && melhor.ToList().Count > 0)
                ViewBag.melhor = melhor.ToList()[0];
            else
            {
                Campos temp = new Campos();
                temp.nome = "Não foram encontrados registos";
                ViewBag.melhor = temp;
            }
            return View();
        }

        public class Campos
        {
            public string nome { get; set; }
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetoM17E/Controllers/LoginController.cs
using Microsoft.Ajax.Utilities;
using ProjetoM17E.Data;
using ProjetoM17E.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ProjetoM17E.Controllers
{
    public class LoginController : Controller
    {
        private ProjetoM17EContext db = new ProjetoM17EContext();

        // GET: Login
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Utilizador utilizador)
        {
            if (utilizador.Email != null && utilizador.Password != null)
            {
                //hash password
                HMACSHA512 hMACSHA512 = new HMACSHA512(new byte[] { 2 });
                var password = hMACSHA512.ComputeHash(Encoding.UTF8.GetBytes(utilizador.Password));
                utilizador.Password = Convert.ToBase64String(password);

                foreach (var u in db.Utilizadors.Where(u => u.Perfil==1).ToList())
                {
                    if (u.Email.ToLower()==utilizador.Email.ToLower() && u.Password==utilizador.Password)
                    {
                        //iniciar sessao
                        FormsAuthentication.SetAuthCookie(utilizador.Email, false);

                        //redirecionar
                        if (Request.QueryString["ReturnUrl"]==null)
                            return RedirectToAction("Index", "Home");
                        else
                            return Redirect(Request.QueryString["ReturnUrl"].ToString());
                    }
                }
            }
            ModelState.AddModelError("", "Login falhou. Tente novamente ou verifique se é adminstrador. ");
            return View(utilizador);
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
    }
}

ProjetoM17E/Views/Shared/_Layout.cshtml
@using ProjetoM17E.Helper
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Entregas</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Entregas", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                        if (User.IsInRole("Administrador"))
                        {
                            <li>@Html.ActionLink("Utilizadores", "Index", "Utilizadores")</li>
                        }
                        <li>@Html.ActionLink("Produtos", "Index", "Produtos")</li>
                        <li>@Html.ActionLink("Clientes", "Index", "Utilizadores")</li>
                        <li>@Html.ActionLink("Entregas", "Index", "Entregas")</li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Consultas</a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Pesquisa Dinamica", "PesquisaDinamica", "Consultas")</li>
                                <li>@Html.ActionLink("Melhor Cliente", "MelhorCliente", "Consultas")</li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                @Html.Raw("Olá "+User.Identity.Name)
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Editar perfil", "Edit/"+ @Html.UserId(User), "Utilizadores")</li>
                                <li>@Html.ActionLink("Terminar sessão", "Logout", "Login")</li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Index", "Login")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>